# Generated by Django 5.1.7 on 2025-03-16 18:39

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('teaching', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Subject',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200, verbose_name='Название предмета')),
                ('description', models.TextField(blank=True, verbose_name='Описание')),
                ('semester', models.IntegerField(verbose_name='Семестр')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('teacher', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='subjects', to='teaching.teacher', verbose_name='Преподаватель')),
            ],
            options={
                'verbose_name': 'Предмет',
                'verbose_name_plural': 'Предметы',
                'ordering': ['-semester', 'name'],
            },
        ),
        migrations.CreateModel(
            name='Schedule',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('day_of_week', models.IntegerField(choices=[(1, 'Понедельник'), (2, 'Вторник'), (3, 'Среда'), (4, 'Четверг'), (5, 'Пятница'), (6, 'Суббота'), (7, 'Воскресенье')], verbose_name='День недели')),
                ('lesson_number', models.IntegerField(choices=[(1, '1 пара (9:00-10:30)'), (2, '2 пара (10:40-12:10)'), (3, '3 пара (12:20-13:50)'), (4, '4 пара (14:30-16:00)'), (5, '5 пара (16:10-17:40)'), (6, '6 пара (17:50-19:20)'), (7, '7 пара (19:30-21:00)')], verbose_name='Номер пары')),
                ('room', models.CharField(max_length=50, verbose_name='Аудитория')),
                ('is_active', models.BooleanField(default=True, verbose_name='Активно')),
                ('teacher', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='schedule_items', to='teaching.teacher', verbose_name='Преподаватель')),
                ('subject', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='schedule_items', to='teaching.subject', verbose_name='Предмет')),
            ],
            options={
                'verbose_name': 'Расписание',
                'verbose_name_plural': 'Расписание',
                'ordering': ['day_of_week', 'lesson_number'],
                'unique_together': {('subject', 'day_of_week', 'lesson_number')},
            },
        ),
        migrations.CreateModel(
            name='Attendance',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField(verbose_name='Дата')),
                ('is_present', models.BooleanField(default=False, verbose_name='Присутствовал')),
                ('note', models.TextField(blank=True, verbose_name='Примечание')),
                ('student', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='attendances', to=settings.AUTH_USER_MODEL, verbose_name='Студент')),
                ('schedule_item', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='attendances', to='teaching.schedule', verbose_name='Занятие')),
            ],
            options={
                'verbose_name': 'Посещаемость',
                'verbose_name_plural': 'Посещаемость',
                'ordering': ['-date', 'schedule_item__lesson_number'],
                'unique_together': {('schedule_item', 'student', 'date')},
            },
        ),
        migrations.CreateModel(
            name='StudentAssignment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.CharField(choices=[('not_submitted', 'Не сдано'), ('submitted', 'На проверке'), ('returned', 'На доработке'), ('completed', 'Проверено')], default='not_submitted', max_length=20, verbose_name='Статус')),
                ('submitted_at', models.DateTimeField(blank=True, null=True, verbose_name='Дата сдачи')),
                ('grade', models.DecimalField(blank=True, decimal_places=2, max_digits=5, null=True, verbose_name='Оценка')),
                ('feedback', models.TextField(blank=True, verbose_name='Комментарий преподавателя')),
                ('assignment', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='student_assignments', to='teaching.assignment', verbose_name='Задание')),
                ('student', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='assignments', to=settings.AUTH_USER_MODEL, verbose_name='Студент')),
            ],
            options={
                'verbose_name': 'Задание студента',
                'verbose_name_plural': 'Задания студентов',
                'ordering': ['-submitted_at'],
                'unique_together': {('student', 'assignment')},
            },
        ),
    ]
