# Generated by Django 5.2 on 2025-04-15 22:37

import django.db.models.deletion
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('teaching', '0002_subject_schedule_attendance_studentassignment'),
    ]

    operations = [
        migrations.CreateModel(
            name='HomeworkSubmission',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('submission_id', models.IntegerField(unique=True)),
                ('student_name', models.CharField(max_length=255)),
                ('assignment_name', models.CharField(max_length=255)),
                ('subject_name', models.CharField(max_length=255)),
                ('received_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('status', models.CharField(choices=[('SUBMITTED', 'Отправлено'), ('REVIEWING', 'На проверке'), ('GRADED', 'Оценено'), ('REJECTED', 'Отклонено')], default='SUBMITTED', max_length=20)),
                ('grade', models.DecimalField(blank=True, decimal_places=2, max_digits=5, null=True)),
                ('feedback', models.TextField(blank=True)),
                ('graded_at', models.DateTimeField(blank=True, null=True)),
            ],
            options={
                'ordering': ['-received_at'],
            },
        ),
    ]
