# Generated by Django 4.2.1 on 2025-04-16 09:41

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('teaching', '0003_homeworksubmission'),
    ]

    operations = [
        migrations.DeleteModel(
            name='HomeworkSubmission',
        ),
    ]
