# Generated by Django 3.2.7 on 2025-04-16 01:37

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('teaching', '0003_homeworksubmission_subjectteacher'),
    ]

    operations = [
        # Удалим операцию создания HomeworkSubmission из предыдущей миграции
        migrations.DeleteModel(
            name='HomeworkSubmission',
        ),
        # Добавим снова только SubjectTeacher
        migrations.CreateModel(
            name='SubjectTeacher',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('role', models.CharField(choices=[('LECTURER', 'Лектор'), ('PRACTICE', 'Руководитель практики'), ('ASSISTANT', 'Ассистент'), ('TUTOR', 'Куратор'), ('LAB', 'Лабораторные работы')], max_length=50, verbose_name='Роль')),
                ('is_main', models.BooleanField(default=False, verbose_name='Основной преподаватель')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('subject', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='teachers_link', to='teaching.subject', verbose_name='Предмет')),
                ('teacher', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='subjects_link', to='teaching.teacher', verbose_name='Преподаватель')),
            ],
            options={
                'verbose_name': 'Связь преподаватель-предмет',
                'verbose_name_plural': 'Связи преподавателей с предметами',
                'unique_together': {('subject', 'teacher', 'role')},
            },
        ),
    ]
