# Generated by Django 5.1.2 on 2025-04-16 08:04

import django.db.models.deletion
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('teaching', '0004_auto_20250416_0137'),
    ]

    operations = [
        migrations.CreateModel(
            name='HomeworkSubmission',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('submission_id', models.IntegerField(unique=True)),
                ('student_name', models.CharField(max_length=255)),
                ('assignment_name', models.CharField(max_length=255)),
                ('subject_name', models.CharField(max_length=255)),
                ('received_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('status', models.CharField(choices=[('SUBMITTED', 'Отправлено'), ('REVIEWING', 'На проверке'), ('GRADED', 'Оценено'), ('REJECTED', 'Отклонено')], default='SUBMITTED', max_length=20)),
                ('grade', models.DecimalField(blank=True, decimal_places=2, max_digits=5, null=True)),
                ('feedback', models.TextField(blank=True)),
                ('graded_at', models.DateTimeField(blank=True, null=True)),
            ],
            options={
                'ordering': ['-received_at'],
            },
        ),
        migrations.AlterModelOptions(
            name='subjectteacher',
            options={'verbose_name': 'Связь предмет-преподаватель', 'verbose_name_plural': 'Связи предмет-преподаватель'},
        ),
        migrations.RemoveField(
            model_name='subjectteacher',
            name='created_at',
        ),
        migrations.RemoveField(
            model_name='subjectteacher',
            name='updated_at',
        ),
        migrations.AlterField(
            model_name='subjectteacher',
            name='role',
            field=models.CharField(choices=[('LECTURER', 'Лектор'), ('PRACTICE', 'Руководитель практики'), ('ASSISTANT', 'Ассистент'), ('TUTOR', 'Куратор'), ('LAB', 'Лабораторные работы')], default='LECTURER', max_length=20, verbose_name='Роль'),
        ),
        migrations.AlterField(
            model_name='subjectteacher',
            name='subject',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='teachers', to='teaching.subject', verbose_name='Предмет'),
        ),
        migrations.AlterField(
            model_name='subjectteacher',
            name='teacher',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='subject_teachers', to='teaching.teacher', verbose_name='Преподаватель'),
        ),
        migrations.CreateModel(
            name='SubjectTeacherGroup',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('group_code', models.CharField(max_length=20, verbose_name='Код группы')),
                ('subject_teacher', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='groups', to='teaching.subjectteacher', verbose_name='Связь предмет-преподаватель')),
            ],
            options={
                'verbose_name': 'Группа преподавателя предмета',
                'verbose_name_plural': 'Группы преподавателей предметов',
                'unique_together': {('subject_teacher', 'group_code')},
            },
        ),
    ]
