# Generated by Django 5.1.2 on 2025-04-16 08:24

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('teaching', '0005_homeworksubmission_alter_subjectteacher_options_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Group',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=20, unique=True, verbose_name='Название группы')),
                ('faculty', models.CharField(blank=True, max_length=100, verbose_name='Факультет')),
                ('year', models.PositiveSmallIntegerField(blank=True, null=True, verbose_name='Год обучения')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Группа',
                'verbose_name_plural': 'Группы',
                'ordering': ['name'],
            },
        ),
        migrations.AlterModelOptions(
            name='subjectteachergroup',
            options={'verbose_name': 'Группа преподавателя предмета (устарело)', 'verbose_name_plural': 'Группы преподавателей предметов (устарело)'},
        ),
        migrations.AlterField(
            model_name='subjectteachergroup',
            name='subject_teacher',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='old_groups', to='teaching.subjectteacher', verbose_name='Связь предмет-преподаватель'),
        ),
        migrations.AddField(
            model_name='subjectteacher',
            name='groups',
            field=models.ManyToManyField(related_name='subject_teachers', to='teaching.group', verbose_name='Группы'),
        ),
    ]
