services:
  auth:
    build: 
      context: ./services/auth
      dockerfile: Dockerfile
    ports:
      - "8002:8002"
    environment:
      - DJANGO_SETTINGS_MODULE=auth_service.settings
      - DEBUG=1
      - ALLOWED_HOSTS=localhost,127.0.0.1,auth
      - CORS_ALLOWED_ORIGINS=http://localhost:3000,http://127.0.0.1:3000,http://localhost:8003,http://localhost:8004
    volumes:
      - ./services/auth:/app
    networks:
      - orioks_network
    restart: unless-stopped

  student_portal:
    build: 
      context: ./services/student_performance
      dockerfile: Dockerfile
    ports:
      - "8003:8003"
    environment:
      - DJANGO_SETTINGS_MODULE=student_performance.settings
      - DEBUG=1
      - ALLOWED_HOSTS=localhost,127.0.0.1,student_portal
      - CORS_ALLOWED_ORIGINS=http://localhost:3000,http://127.0.0.1:3000,http://localhost:8002,http://localhost:8004
      - USE_SQLITE=True
    volumes:
      - ./services/student_performance:/app
    depends_on:
      - auth
    networks:
      - orioks_network
    restart: unless-stopped

  teacher_portal:
    build: 
      context: ./services/teacher_portal
      dockerfile: Dockerfile
    ports:
      - "8004:8004"
    environment:
      - DJANGO_SETTINGS_MODULE=teacher_portal.settings
      - DEBUG=1
      - ALLOWED_HOSTS=localhost,127.0.0.1,teacher_portal
      - CORS_ALLOWED_ORIGINS=http://localhost:3000,http://127.0.0.1:3000,http://localhost:8002,http://localhost:8003
    volumes:
      - ./services/teacher_portal:/app
    depends_on:
      - auth
    networks:
      - orioks_network
    restart: unless-stopped

networks:
  orioks_network:
    driver: bridge 