# Generated by Django 5.1.2 on 2025-04-15 22:01

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('performance', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Teacher',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('user_id', models.IntegerField(unique=True, verbose_name='ID пользователя')),
                ('first_name', models.CharField(max_length=100, verbose_name='Имя')),
                ('last_name', models.CharField(max_length=100, verbose_name='Фамилия')),
                ('middle_name', models.CharField(blank=True, max_length=100, null=True, verbose_name='Отчество')),
                ('academic_degree', models.CharField(blank=True, max_length=100, null=True, verbose_name='Ученая степень')),
                ('academic_title', models.CharField(blank=True, max_length=100, null=True, verbose_name='Ученое звание')),
                ('department', models.CharField(blank=True, max_length=200, null=True, verbose_name='Кафедра')),
                ('position', models.CharField(blank=True, max_length=100, null=True, verbose_name='Должность')),
                ('email', models.EmailField(blank=True, max_length=254, null=True, verbose_name='Email')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Преподаватель',
                'verbose_name_plural': 'Преподаватели',
                'ordering': ['last_name', 'first_name'],
            },
        ),
        migrations.CreateModel(
            name='SubjectTeacher',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('is_main', models.BooleanField(default=False, verbose_name='Основной преподаватель')),
                ('role', models.CharField(choices=[('LECTURER', 'Лектор'), ('PRACTICIAN', 'Практик'), ('ASSISTANT', 'Ассистент'), ('EXAMINER', 'Экзаменатор')], default='LECTURER', max_length=100, verbose_name='Роль')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('subject', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='teachers_link', to='performance.subject', verbose_name='Предмет')),
                ('teacher', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='subjects_link', to='performance.teacher', verbose_name='Преподаватель')),
            ],
            options={
                'verbose_name': 'Связь предмет-преподаватель',
                'verbose_name_plural': 'Связи предмет-преподаватель',
                'ordering': ['subject', 'is_main', 'role'],
                'unique_together': {('subject', 'teacher', 'role')},
            },
        ),
    ]
