# Generated by Django 4.2.20 on 2025-03-19 12:12

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('performance', '0002_homeworkassignment_remove_student_user_id_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='homeworkassignment',
            options={'ordering': ['-deadline']},
        ),
        migrations.RemoveField(
            model_name='homeworkassignment',
            name='max_points',
        ),
        migrations.AddField(
            model_name='homeworkassignment',
            name='updated_at',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AlterField(
            model_name='homeworkassignment',
            name='name',
            field=models.CharField(max_length=255),
        ),
        migrations.AlterField(
            model_name='homeworkassignment',
            name='subject',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='assignments', to='performance.subject'),
        ),
    ]
