# Generated by Django 5.1.2 on 2025-04-16 10:05

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Schedule',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('day_of_week', models.CharField(choices=[('MON', 'Понедельник'), ('TUE', 'Вторник'), ('WED', 'Среда'), ('THU', 'Четверг'), ('FRI', 'Пятница'), ('SAT', 'Суббота')], max_length=3, verbose_name='День недели')),
                ('lesson_number', models.CharField(choices=[('1', '08:30 - 10:00'), ('2', '10:10 - 11:40'), ('3', '11:50 - 13:20'), ('4', '13:30 - 15:00'), ('5', '15:10 - 16:40'), ('6', '16:50 - 18:20')], max_length=1, verbose_name='Номер пары')),
                ('subject', models.CharField(max_length=255, verbose_name='Предмет')),
                ('teacher', models.CharField(max_length=255, verbose_name='Преподаватель')),
                ('classroom', models.CharField(max_length=50, verbose_name='Аудитория')),
                ('group', models.CharField(max_length=50, verbose_name='Группа')),
                ('semester', models.CharField(max_length=50, verbose_name='Семестр')),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now, verbose_name='Дата создания')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Дата обновления')),
            ],
            options={
                'verbose_name': 'Расписание',
                'verbose_name_plural': 'Расписание',
                'ordering': ['day_of_week', 'lesson_number'],
            },
        ),
    ]
