# Generated by Django 5.1.2 on 2025-04-16 11:28

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('schedule', '0002_group_alter_schedule_group'),
    ]

    operations = [
        migrations.CreateModel(
            name='Subject',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200, verbose_name='Название предмета')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Предмет',
                'verbose_name_plural': 'Предметы',
                'ordering': ['name'],
            },
        ),
        migrations.RenameField(
            model_name='schedule',
            old_name='classroom',
            new_name='room',
        ),
        migrations.AddField(
            model_name='schedule',
            name='is_lecture',
            field=models.BooleanField(default=True, verbose_name='Лекция'),
        ),
        migrations.AlterField(
            model_name='group',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True),
        ),
        migrations.AlterField(
            model_name='group',
            name='name',
            field=models.CharField(max_length=50, verbose_name='Название группы'),
        ),
        migrations.AlterField(
            model_name='group',
            name='updated_at',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AlterField(
            model_name='schedule',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True),
        ),
        migrations.AlterField(
            model_name='schedule',
            name='day_of_week',
            field=models.IntegerField(choices=[(1, 'Понедельник'), (2, 'Вторник'), (3, 'Среда'), (4, 'Четверг'), (5, 'Пятница'), (6, 'Суббота'), (7, 'Воскресенье')], verbose_name='День недели'),
        ),
        migrations.AlterField(
            model_name='schedule',
            name='group',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='schedule_items', to='schedule.group', verbose_name='Группа'),
        ),
        migrations.AlterField(
            model_name='schedule',
            name='lesson_number',
            field=models.IntegerField(choices=[(1, '1 пара (9:00-10:30)'), (2, '2 пара (10:45-12:15)'), (3, '3 пара (13:00-14:30)'), (4, '4 пара (14:45-16:15)'), (5, '5 пара (16:30-18:00)'), (6, '6 пара (18:15-19:45)')], verbose_name='Номер пары'),
        ),
        migrations.AlterField(
            model_name='schedule',
            name='semester',
            field=models.IntegerField(choices=[(1, 'Первый семестр'), (2, 'Второй семестр'), (3, 'Третий семестр'), (4, 'Четвертый семестр'), (5, 'Пятый семестр'), (6, 'Шестой семестр'), (7, 'Седьмой семестр'), (8, 'Восьмой семестр')], verbose_name='Семестр'),
        ),
        migrations.AlterField(
            model_name='schedule',
            name='teacher',
            field=models.CharField(max_length=200, verbose_name='Преподаватель'),
        ),
        migrations.AlterField(
            model_name='schedule',
            name='updated_at',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AlterUniqueTogether(
            name='schedule',
            unique_together={('day_of_week', 'lesson_number', 'room', 'semester', 'group')},
        ),
        migrations.AlterField(
            model_name='schedule',
            name='subject',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='schedule_items', to='schedule.subject', verbose_name='Предмет'),
        ),
    ]
