# Generated by Django 5.1.2 on 2025-04-16 11:59

import django.db.models.deletion
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('schedule', '0003_subject_rename_classroom_schedule_room_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='schedule',
            name='subject',
            field=models.CharField(max_length=200, verbose_name='Предмет'),
        ),
        migrations.AlterModelOptions(
            name='group',
            options={'verbose_name': 'Группа', 'verbose_name_plural': 'Группы'},
        ),
        migrations.AlterUniqueTogether(
            name='schedule',
            unique_together=set(),
        ),
        migrations.AlterField(
            model_name='group',
            name='created_at',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
        migrations.AlterField(
            model_name='group',
            name='name',
            field=models.CharField(max_length=100, unique=True),
        ),
        migrations.AlterField(
            model_name='schedule',
            name='created_at',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
        migrations.AlterField(
            model_name='schedule',
            name='day_of_week',
            field=models.CharField(choices=[('monday', 'Понедельник'), ('tuesday', 'Вторник'), ('wednesday', 'Среда'), ('thursday', 'Четверг'), ('friday', 'Пятница'), ('saturday', 'Суббота')], max_length=10, verbose_name='День недели'),
        ),
        migrations.AlterField(
            model_name='schedule',
            name='group',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='schedule.group', verbose_name='Группа'),
        ),
        migrations.AlterField(
            model_name='schedule',
            name='is_lecture',
            field=models.BooleanField(default=False, verbose_name='Лекция'),
        ),
        migrations.AlterField(
            model_name='schedule',
            name='lesson_number',
            field=models.IntegerField(verbose_name='Номер пары'),
        ),
        migrations.AlterField(
            model_name='schedule',
            name='semester',
            field=models.IntegerField(verbose_name='Семестр'),
        ),
        migrations.DeleteModel(
            name='Subject',
        ),
    ]
