# Generated by Django 5.1.2 on 2025-04-16 12:18

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('schedule', '0004_alter_schedule_subject_alter_group_options_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='schedule',
            name='group',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='schedule.group', to_field='name', verbose_name='Группа'),
        ),
        migrations.AlterModelTable(
            name='group',
            table='student_performance_group',
        ),
    ]
