# Generated by Django 4.2.20 on 2025-03-19 00:52

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('auth_app', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='WebAuthnCredential',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('credential_id', models.BinaryField(unique=True, verbose_name='ID учетных данных')),
                ('credential_public_key', models.BinaryField(verbose_name='Публичный ключ')),
                ('credential_name', models.CharField(max_length=100, verbose_name='Название ключа безопасности')),
                ('sign_count', models.BigIntegerField(default=0, verbose_name='Счетчик подписей')),
                ('rp_id', models.CharField(max_length=255, verbose_name='ID доверенной стороны')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Дата создания')),
                ('last_used_at', models.DateTimeField(blank=True, null=True, verbose_name='Последнее использование')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='webauthn_credentials', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Ключ WebAuthn',
                'verbose_name_plural': 'Ключи WebAuthn',
            },
        ),
    ]
