# Generated by Django 5.1.2 on 2024-11-05 16:24

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('records', '0005_alter_student_user'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='student',
            name='user',
        ),
    ]
