# Generated by Django 5.1.2 on 2024-11-11 19:25

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('records', '0007_alter_student_group'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Internship',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('company', models.CharField(max_length=255, verbose_name='Компания')),
                ('company_representative', models.CharField(max_length=255, verbose_name='Представитель компании')),
                ('contact_details', models.TextField(verbose_name='Контактные данные компании')),
                ('is_academic_supervisor', models.BooleanField(verbose_name='Научный руководитель МИЭТ')),
                ('is_company_supervisor', models.BooleanField(verbose_name='Руководитель от предприятия')),
            ],
        ),
        migrations.AddField(
            model_name='grade',
            name='date_of_grade',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='student',
            name='user',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
    ]
