# Generated by Django 5.1.2 on 2024-11-11 19:59

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('records', '0008_internship_grade_date_of_grade_student_user'),
    ]

    operations = [
        migrations.CreateModel(
            name='Homework',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255)),
                ('description', models.TextField()),
                ('due_date', models.DateField()),
                ('files', models.FileField(blank=True, null=True, upload_to='homework_files/')),
                ('professor', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='records.professor')),
            ],
        ),
        migrations.CreateModel(
            name='HomeworkFile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('file', models.FileField(blank=True, null=True, upload_to='homework_files/')),
                ('homework', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='homework_files', to='records.homework')),
            ],
        ),
    ]
